/* lib/manifest.js — Culpeo brand data. Edit prices, contacts and copy here. */
(function () {
  "use strict";

  var i18n = {
    es: {
      "brand.tagline": "Indumentaria outdoor, para quienes eligen su terreno.",
      "nav.home": "Inicio", "nav.products": "Productos", "nav.about": "Nosotros",
      "nav.sizeguide": "Guía de tallas", "nav.cart": "Carro",
      "nav.language": "Idioma",
      "hero.kicker": "Culpeo · Inspirado en la naturaleza",
      "hero.title.line1": "Hecho para explorar.", "hero.title.line2": "Pensado para durar.",
      "hero.subtitle": "Piezas de edición limitada, inspiradas en la naturaleza: paisajes, flora y fauna de distintos rincones del mundo.",
      "hero.cta.shop": "Ver colección",
      "manifesto.kicker": "Origen",
      "manifesto.title": "No diseñamos para la ciudad. Diseñamos para el camino a la ciudad.",
      "manifesto.body": "Culpeo nace en Chile, entre el desierto más árido del mundo y el hielo austral — y desde ahí mira hacia el resto del planeta. Cada pieza se piensa para quien no se queda quieto: el que sale de excursión el fin de semana, el que cruza fronteras, quien prefiere un paisaje nuevo a una vitrina.",
      "pillars.materials.title": "Base de calidad",
      "pillars.materials.body": "Partimos de estructuras ya probadas y confiables. Ahí ponemos el esfuerzo: en el diseño, la paleta y el bordado — no en promesas técnicas que no necesitas.",
      "pillars.design.title": "Diseño con origen",
      "pillars.design.body": "Paletas, nombres y formas tomados de la naturaleza — paisajes, flora y fauna de distintos rincones del mundo — no de una tendencia de temporada.",
      "pillars.exclusivity.title": "Tirada limitada",
      "pillars.exclusivity.body": "Producimos en lotes pequeños. Cuando una pieza se agota, no vuelve en la misma versión.",
      "featured.kicker": "Colección actual", "featured.title": "Piezas Culpeo", "featured.cta": "Ver todo el catálogo",
      "ctaFinal.title": "Reserva tu pieza antes de que se agote el lote.",
      "ctaFinal.body": "Escríbenos por WhatsApp — coordinamos talla, color y despacho contigo directamente.",
      "ctaFinal.button": "Escribir por WhatsApp",
      "footer.tagline": "Marca de indumentaria outdoor.",
      "footer.explore": "Explorar", "footer.social": "Síguenos", "footer.credits": "Créditos fotográficos",
      "footer.rights": "Todos los derechos reservados.",
      "products.kicker": "Catálogo", "products.title": "Piezas Culpeo",
      "products.subtitle": "Diseño propio, producido en lotes limitados.",
      "product.addToCart": "Agregar al carro", "product.viewDetail": "Ver detalle", "product.from": "Desde",
      "product.materialText": "Estructura trucker 5 paneles, base Yupoong Retro Trucker, snapback ajustable de 6 posiciones, malla trasera transpirable, visera pre-curvada.",
      "productDetail.back": "Volver al catálogo", "productDetail.material": "Material",
      "productDetail.sizing": "¿Qué talla elijo?", "productDetail.sizingLink": "Ver guía de tallas",
      "productDetail.color": "Color", "productDetail.quantity": "Cantidad",
      "productDetail.addToCart": "Agregar al carro", "productDetail.added": "Agregado al carro",
      "productDetail.descriptionHeading": "Detalle",
      "productDetail.careHeading": "Cuidado",
      "productDetail.careBody": "Lavar a mano con agua fría. No usar secadora. Dejar secar a la sombra sobre su forma para conservar la curva de la visera.",
      "about.kicker": "Nosotros", "about.title": "Culpeo — como el zorro que cruza cualquier terreno",
      "about.intro": "El culpeo es el zorro andino más grande de Sudamérica: se mueve igual de bien en el desierto, el bosque y la nieve. Tomamos su nombre porque así entendemos el vestuario outdoor — una sola pieza, capaz de acompañarte en terrenos distintos.",
      "about.mission.title": "Por qué existimos",
      "about.mission.body": "Chile tiene una de las geografías más extremas y diversas del planeta, pero gran parte del vestuario outdoor que se vende aquí se diseña en otro hemisferio, para otro clima. Culpeo diseña desde el territorio que va a usarlo.",
      "about.craft.title": "Cómo trabajamos",
      "about.craft.body": "Diseñamos cada modelo en Chile: paleta, nombre y bordado nacen acá, sobre una base de calidad ya probada en el mercado. Trabajamos en lotes pequeños para controlar cada detalle antes de lanzar algo nuevo.",
      "about.origin.title": "Recién empezamos",
      "about.origin.body": "Culpeo es una marca joven. Cada colección que lancemos será más ambiciosa que la anterior — y cada una llevará el nombre de un lugar que vale la pena proteger.",
      "sizeguide.kicker": "Guía", "sizeguide.title": "Guía de tallas",
      "sizeguide.intro": "Todas nuestras gorras usan una estructura trucker snapback: talla única, ajustable en la parte trasera. Así se adapta a la mayoría de las cabezas adultas sin perder calce.",
      "sizeguide.howto.title": "Cómo medir tu cabeza",
      "sizeguide.howto.body": "Con una huincha de medir, rodea tu cabeza justo por encima de las orejas y las cejas. Ese número en centímetros es tu referencia — todas nuestras gorras cubren ese rango con el snapback.",
      "sizeguide.table.size": "Talla", "sizeguide.table.range": "Circunferencia", "sizeguide.table.fit": "Ajuste",
      "sizeguide.adjustable.name": "Única ajustable",
      "sizeguide.adjustable.fit": "Snapback de 6 posiciones — se adapta perfecto de extremo a extremo",
      "sizeguide.tip.title": "Un detalle que ayuda",
      "sizeguide.tip.body": "Si tu cabeza está entre dos posiciones del snapback, deja la gorra un poco más suelta: el mesh trasero se acomoda solo con el uso.",
      "cart.title": "Tu carro", "cart.empty": "Tu carro está vacío por ahora.", "cart.emptyCta": "Ver colección",
      "cart.item.remove": "Quitar", "cart.item.color": "Color", "cart.item.qty": "Cantidad",
      "cart.subtotal": "Subtotal", "cart.total": "Total", "cart.checkout": "Finalizar por WhatsApp",
      "cart.checkoutNote": "Al finalizar se abre WhatsApp con el detalle de tu pedido. Coordinamos pago y despacho directamente contigo.",
      "cart.continue": "Seguir comprando",
      "credits.title": "Créditos fotográficos",
      "credits.intro": "Imágenes bajo licencias Creative Commons, vía Openverse / Wikimedia Commons.",
      "credits.back": "Volver al inicio",
      "footer.faq": "Preguntas frecuentes",
      "faq.kicker": "Ayuda", "faq.title": "Preguntas frecuentes",
      "faq.intro": "Lo que más nos preguntan antes de comprar. ¿No está tu duda? Escríbenos por WhatsApp.",
      "howtobuy.kicker": "Cómo comprar", "howtobuy.title": "Del carro a tu casa, en 3 pasos",
      "howtobuy.step1.title": "1. Elige tu pieza", "howtobuy.step1.body": "Agrégala al carro con el color y la cantidad que quieras.",
      "howtobuy.step2.title": "2. Revisa tu pedido", "howtobuy.step2.body": "Ajusta cantidades o quita productos antes de finalizar.",
      "howtobuy.step3.title": "3. Finaliza por WhatsApp", "howtobuy.step3.body": "Se abre WhatsApp con tu pedido armado. Ahí coordinamos pago y despacho.",
      "product.stock.low": "Últimas unidades", "product.stock.soldOut": "Agotado"
    },
    en: {
      "brand.tagline": "Outdoor apparel, for those who choose their own terrain.",
      "nav.home": "Home", "nav.products": "Shop", "nav.about": "About",
      "nav.sizeguide": "Size Guide", "nav.cart": "Cart",
      "nav.language": "Language",
      "hero.kicker": "Culpeo · Inspired by nature",
      "hero.title.line1": "Made to explore.", "hero.title.line2": "Built to last.",
      "hero.subtitle": "Limited-edition pieces, inspired by nature: landscapes, flora and fauna from different corners of the world.",
      "hero.cta.shop": "Shop the collection",
      "manifesto.kicker": "Origin",
      "manifesto.title": "We don't design for the city. We design for the road out of it.",
      "manifesto.body": "Culpeo was born in Chile, between the driest desert on earth and the southern ice — and looks out from there toward the rest of the planet. Every piece is made for whoever doesn't sit still: the weekend explorer, the traveler crossing borders, whoever would rather find a new landscape than a shop window.",
      "pillars.materials.title": "A solid base",
      "pillars.materials.body": "We start from product bases that are already proven and reliable. That's where we put the effort: design, palette and embroidery — not technical promises you don't need.",
      "pillars.design.title": "Design with origin",
      "pillars.design.body": "Palettes, names and shapes drawn from nature — landscapes, flora and fauna from different corners of the world — not from a seasonal trend.",
      "pillars.exclusivity.title": "Limited runs",
      "pillars.exclusivity.body": "We produce in small batches. Once a piece sells out, it doesn't come back in the same version.",
      "featured.kicker": "Current collection", "featured.title": "Culpeo pieces", "featured.cta": "See the full catalog",
      "ctaFinal.title": "Reserve your piece before the run sells out.",
      "ctaFinal.body": "Message us on WhatsApp — we'll sort size, color and shipping directly with you.",
      "ctaFinal.button": "Message on WhatsApp",
      "footer.tagline": "Outdoor apparel brand.",
      "footer.explore": "Explore", "footer.social": "Follow", "footer.credits": "Photo credits",
      "footer.rights": "All rights reserved.",
      "products.kicker": "Catalog", "products.title": "Culpeo pieces",
      "products.subtitle": "Original design, produced in limited batches.",
      "product.addToCart": "Add to cart", "product.viewDetail": "View detail", "product.from": "From",
      "product.materialText": "5-panel trucker structure, Yupoong Retro Trucker base, 6-position adjustable snapback, breathable back mesh, pre-curved bill.",
      "productDetail.back": "Back to catalog", "productDetail.material": "Material",
      "productDetail.sizing": "Which size should I get?", "productDetail.sizingLink": "See size guide",
      "productDetail.color": "Color", "productDetail.quantity": "Quantity",
      "productDetail.addToCart": "Add to cart", "productDetail.added": "Added to cart",
      "productDetail.descriptionHeading": "Detail",
      "productDetail.careHeading": "Care",
      "productDetail.careBody": "Hand wash in cold water. Do not tumble dry. Air dry in the shade on its shape to keep the brim curve.",
      "about.kicker": "About", "about.title": "Culpeo — like the fox that crosses any terrain",
      "about.intro": "The culpeo is South America's largest Andean fox: equally at home in desert, forest and snow. We took its name because that's how we think about outdoor apparel — one piece, built to follow you across different ground.",
      "about.mission.title": "Why we exist",
      "about.mission.body": "Chile has one of the most extreme and diverse geographies on the planet, yet most outdoor apparel sold here is designed on another hemisphere, for another climate. Culpeo designs from the territory that will actually wear it.",
      "about.craft.title": "How we work",
      "about.craft.body": "We design every model in Chile: palette, name and embroidery are born here, built on a quality base already proven in the market. We work in small batches, so we can control every detail before launching something new.",
      "about.origin.title": "We're just getting started",
      "about.origin.body": "Culpeo is a young brand. Every collection we launch will be more ambitious than the last — and each one will carry the name of a place worth protecting.",
      "sizeguide.kicker": "Guide", "sizeguide.title": "Size guide",
      "sizeguide.intro": "All our caps use a snapback trucker structure: one size, adjustable at the back. That fits most adult heads without losing its shape.",
      "sizeguide.howto.title": "How to measure your head",
      "sizeguide.howto.body": "With a tape measure, wrap it around your head just above your ears and eyebrows. That number in centimeters is your reference — all our caps cover that range with the snapback.",
      "sizeguide.table.size": "Size", "sizeguide.table.range": "Circumference", "sizeguide.table.fit": "Fit",
      "sizeguide.adjustable.name": "One size, adjustable",
      "sizeguide.adjustable.fit": "6-position snapback — fits comfortably end to end",
      "sizeguide.tip.title": "One detail that helps",
      "sizeguide.tip.body": "If you're between two snap positions, leave the cap a touch looser: the back mesh breaks in with wear.",
      "cart.title": "Your cart", "cart.empty": "Your cart is empty for now.", "cart.emptyCta": "See the collection",
      "cart.item.remove": "Remove", "cart.item.color": "Color", "cart.item.qty": "Quantity",
      "cart.subtotal": "Subtotal", "cart.total": "Total", "cart.checkout": "Checkout via WhatsApp",
      "cart.checkoutNote": "Checking out opens WhatsApp with your order detail. We sort payment and shipping directly with you.",
      "cart.continue": "Continue shopping",
      "credits.title": "Photo credits",
      "credits.intro": "Images under Creative Commons licenses, via Openverse / Wikimedia Commons.",
      "credits.back": "Back to home",
      "footer.faq": "FAQ",
      "faq.kicker": "Help", "faq.title": "Frequently asked questions",
      "faq.intro": "What people ask us most before buying. Don't see your question? Message us on WhatsApp.",
      "howtobuy.kicker": "How to buy", "howtobuy.title": "From cart to your door, in 3 steps",
      "howtobuy.step1.title": "1. Pick your piece", "howtobuy.step1.body": "Add it to your cart with the color and quantity you want.",
      "howtobuy.step2.title": "2. Review your order", "howtobuy.step2.body": "Adjust quantities or remove items before checking out.",
      "howtobuy.step3.title": "3. Check out via WhatsApp", "howtobuy.step3.body": "WhatsApp opens with your order ready. From there we sort payment and shipping.",
      "product.stock.low": "Low stock", "product.stock.soldOut": "Sold out"
    },
    it: {
      "brand.tagline": "Abbigliamento outdoor, per chi sceglie il proprio terreno.",
      "nav.home": "Home", "nav.products": "Shop", "nav.about": "Chi siamo",
      "nav.sizeguide": "Guida alle taglie", "nav.cart": "Carrello",
      "nav.language": "Lingua",
      "hero.kicker": "Culpeo · Ispirato dalla natura",
      "hero.title.line1": "Fatto per esplorare.", "hero.title.line2": "Costruito per durare.",
      "hero.subtitle": "Pezzi in edizione limitata, ispirati alla natura: paesaggi, flora e fauna di diversi angoli del mondo.",
      "hero.cta.shop": "Vedi la collezione",
      "manifesto.kicker": "Origine",
      "manifesto.title": "Non progettiamo per la città. Progettiamo per la strada che ne esce.",
      "manifesto.body": "Culpeo nasce in Cile, tra il deserto più arido del mondo e i ghiacci australi — e da lì guarda al resto del pianeta. Ogni pezzo è pensato per chi non sta fermo: chi esce in escursione nel weekend, chi attraversa confini, chi preferisce un paesaggio nuovo a una vetrina.",
      "pillars.materials.title": "Una base solida",
      "pillars.materials.body": "Partiamo da basi già collaudate e affidabili. È lì che mettiamo l'impegno: design, palette e ricamo — non promesse tecniche che non ti servono.",
      "pillars.design.title": "Design con origine",
      "pillars.design.body": "Palette, nomi e forme presi dalla natura — paesaggi, flora e fauna da diversi angoli del mondo — non da una tendenza stagionale.",
      "pillars.exclusivity.title": "Serie limitate",
      "pillars.exclusivity.body": "Produciamo in piccoli lotti. Quando un pezzo esaurisce, non torna nella stessa versione.",
      "featured.kicker": "Collezione attuale", "featured.title": "Pezzi Culpeo", "featured.cta": "Vedi tutto il catalogo",
      "ctaFinal.title": "Prenota il tuo pezzo prima che il lotto finisca.",
      "ctaFinal.body": "Scrivici su WhatsApp — definiamo taglia, colore e spedizione direttamente con te.",
      "ctaFinal.button": "Scrivi su WhatsApp",
      "footer.tagline": "Marchio di abbigliamento outdoor.",
      "footer.explore": "Esplora", "footer.social": "Seguici", "footer.credits": "Crediti fotografici",
      "footer.rights": "Tutti i diritti riservati.",
      "products.kicker": "Catalogo", "products.title": "Pezzi Culpeo",
      "products.subtitle": "Design originale, prodotto in lotti limitati.",
      "product.addToCart": "Aggiungi al carrello", "product.viewDetail": "Vedi dettaglio", "product.from": "Da",
      "product.materialText": "Struttura trucker a 5 pannelli, base Yupoong Retro Trucker, snapback regolabile a 6 posizioni, rete posteriore traspirante, visiera pre-curvata.",
      "productDetail.back": "Torna al catalogo", "productDetail.material": "Materiale",
      "productDetail.sizing": "Che taglia scelgo?", "productDetail.sizingLink": "Vedi guida alle taglie",
      "productDetail.color": "Colore", "productDetail.quantity": "Quantità",
      "productDetail.addToCart": "Aggiungi al carrello", "productDetail.added": "Aggiunto al carrello",
      "productDetail.descriptionHeading": "Dettaglio",
      "productDetail.careHeading": "Cura",
      "productDetail.careBody": "Lavare a mano in acqua fredda. Non asciugare in asciugatrice. Asciugare all'ombra mantenendo la forma per conservare la curva della visiera.",
      "about.kicker": "Chi siamo", "about.title": "Culpeo — come la volpe che attraversa ogni terreno",
      "about.intro": "Il culpeo è la volpe andina più grande del Sudamerica: si muove bene nel deserto, nel bosco e nella neve. Abbiamo scelto il suo nome perché così intendiamo l'abbigliamento outdoor — un solo capo, capace di accompagnarti su terreni diversi.",
      "about.mission.title": "Perché esistiamo",
      "about.mission.body": "Il Cile ha una delle geografie più estreme e diverse del pianeta, eppure gran parte dell'abbigliamento outdoor venduto qui è progettato in un altro emisfero, per un altro clima. Culpeo progetta a partire dal territorio che lo indosserà davvero.",
      "about.craft.title": "Come lavoriamo",
      "about.craft.body": "Progettiamo ogni modello in Cile: palette, nome e ricamo nascono qui, su una base di qualità già collaudata sul mercato. Lavoriamo in piccoli lotti, per controllare ogni dettaglio prima di lanciare qualcosa di nuovo.",
      "about.origin.title": "Siamo appena all'inizio",
      "about.origin.body": "Culpeo è un marchio giovane. Ogni collezione che lanceremo sarà più ambiziosa della precedente — e ciascuna porterà il nome di un luogo che vale la pena proteggere.",
      "sizeguide.kicker": "Guida", "sizeguide.title": "Guida alle taglie",
      "sizeguide.intro": "Tutti i nostri cappelli hanno una struttura trucker snapback: taglia unica, regolabile sul retro. Si adatta così alla maggior parte delle teste adulte senza perdere la forma.",
      "sizeguide.howto.title": "Come misurare la testa",
      "sizeguide.howto.body": "Con un metro da sarta, avvolgilo intorno alla testa appena sopra le orecchie e le sopracciglia. Quel numero in centimetri è il tuo riferimento — tutti i nostri cappelli coprono quel range con lo snapback.",
      "sizeguide.table.size": "Taglia", "sizeguide.table.range": "Circonferenza", "sizeguide.table.fit": "Vestibilità",
      "sizeguide.adjustable.name": "Taglia unica regolabile",
      "sizeguide.adjustable.fit": "Snapback a 6 posizioni — calza comoda da un estremo all'altro",
      "sizeguide.tip.title": "Un dettaglio utile",
      "sizeguide.tip.body": "Se sei tra due posizioni dello snapback, lascia il cappello un po' più largo: la rete posteriore si adatta da sola con l'uso.",
      "cart.title": "Il tuo carrello", "cart.empty": "Il tuo carrello è vuoto per ora.", "cart.emptyCta": "Vedi la collezione",
      "cart.item.remove": "Rimuovi", "cart.item.color": "Colore", "cart.item.qty": "Quantità",
      "cart.subtotal": "Subtotale", "cart.total": "Totale", "cart.checkout": "Concludi su WhatsApp",
      "cart.checkoutNote": "Concludendo si apre WhatsApp con il dettaglio del tuo ordine. Definiamo pagamento e spedizione direttamente con te.",
      "cart.continue": "Continua lo shopping",
      "credits.title": "Crediti fotografici",
      "credits.intro": "Immagini con licenze Creative Commons, via Openverse / Wikimedia Commons.",
      "credits.back": "Torna alla home",
      "footer.faq": "Domande frequenti",
      "faq.kicker": "Aiuto", "faq.title": "Domande frequenti",
      "faq.intro": "Le domande più comuni prima di acquistare. Non trovi la tua? Scrivici su WhatsApp.",
      "howtobuy.kicker": "Come acquistare", "howtobuy.title": "Dal carrello a casa tua, in 3 passi",
      "howtobuy.step1.title": "1. Scegli il tuo pezzo", "howtobuy.step1.body": "Aggiungilo al carrello con il colore e la quantità che vuoi.",
      "howtobuy.step2.title": "2. Controlla il tuo ordine", "howtobuy.step2.body": "Modifica le quantità o rimuovi prodotti prima di concludere.",
      "howtobuy.step3.title": "3. Concludi su WhatsApp", "howtobuy.step3.body": "Si apre WhatsApp con il tuo ordine pronto. Da lì definiamo pagamento e spedizione.",
      "product.stock.low": "Ultimi pezzi", "product.stock.soldOut": "Esaurito"
    },
    de: {
      "brand.tagline": "Outdoor-Bekleidung, für alle, die ihr eigenes Terrain wählen.",
      "nav.home": "Start", "nav.products": "Shop", "nav.about": "Über uns",
      "nav.sizeguide": "Größenberater", "nav.cart": "Warenkorb",
      "nav.language": "Sprache",
      "hero.kicker": "Culpeo · Inspiriert von der Natur",
      "hero.title.line1": "Gemacht zum Entdecken.", "hero.title.line2": "Gebaut, um zu bleiben.",
      "hero.subtitle": "Stücke in limitierter Auflage, inspiriert von der Natur: Landschaften, Flora und Fauna aus verschiedenen Teilen der Welt.",
      "hero.cta.shop": "Kollektion ansehen",
      "manifesto.kicker": "Ursprung",
      "manifesto.title": "Wir entwerfen nicht für die Stadt. Wir entwerfen für den Weg aus ihr hinaus.",
      "manifesto.body": "Culpeo entstand in Chile, zwischen der trockensten Wüste der Welt und dem südlichen Eis — und blickt von dort auf den Rest des Planeten. Jedes Stück ist für jene gemacht, die nicht stillstehen: den Wochenend-Entdecker, den Reisenden, der Grenzen überquert, wer eine neue Landschaft einem Schaufenster vorzieht.",
      "pillars.materials.title": "Eine solide Basis",
      "pillars.materials.body": "Wir starten mit bewährten, zuverlässigen Basisstrukturen. Dort investieren wir unsere Mühe: Design, Farbpalette und Stickerei — keine technischen Versprechen, die du nicht brauchst.",
      "pillars.design.title": "Design mit Herkunft",
      "pillars.design.body": "Paletten, Namen und Formen aus der Natur — Landschaften, Flora und Fauna aus verschiedenen Teilen der Welt — nicht aus einem saisonalen Trend.",
      "pillars.exclusivity.title": "Limitierte Auflagen",
      "pillars.exclusivity.body": "Wir produzieren in kleinen Chargen. Ist ein Stück ausverkauft, kommt es nicht in derselben Version zurück.",
      "featured.kicker": "Aktuelle Kollektion", "featured.title": "Culpeo Stücke", "featured.cta": "Gesamten Katalog ansehen",
      "ctaFinal.title": "Sichere dir dein Stück, bevor die Charge ausverkauft ist.",
      "ctaFinal.body": "Schreib uns auf WhatsApp — wir klären Größe, Farbe und Versand direkt mit dir.",
      "ctaFinal.button": "Auf WhatsApp schreiben",
      "footer.tagline": "Marke für Outdoor-Bekleidung.",
      "footer.explore": "Entdecken", "footer.social": "Folgen", "footer.credits": "Bildnachweise",
      "footer.rights": "Alle Rechte vorbehalten.",
      "products.kicker": "Katalog", "products.title": "Culpeo Stücke",
      "products.subtitle": "Eigenes Design, in limitierten Chargen produziert.",
      "product.addToCart": "In den Warenkorb", "product.viewDetail": "Details ansehen", "product.from": "Ab",
      "product.materialText": "5-Panel-Trucker-Struktur, Yupoong-Retro-Trucker-Basis, 6-Positionen-Snapback, atmungsaktives Rückenmesh, vorgeformter Schirm.",
      "productDetail.back": "Zurück zum Katalog", "productDetail.material": "Material",
      "productDetail.sizing": "Welche Größe passt zu mir?", "productDetail.sizingLink": "Größenberater ansehen",
      "productDetail.color": "Farbe", "productDetail.quantity": "Menge",
      "productDetail.addToCart": "In den Warenkorb", "productDetail.added": "Zum Warenkorb hinzugefügt",
      "productDetail.descriptionHeading": "Details",
      "productDetail.careHeading": "Pflege",
      "productDetail.careBody": "Handwäsche in kaltem Wasser. Nicht im Trockner trocknen. Im Schatten auf seiner Form trocknen lassen, um die Schirmkurve zu erhalten.",
      "about.kicker": "Über uns", "about.title": "Culpeo — wie der Fuchs, der jedes Terrain durchquert",
      "about.intro": "Der Culpeo ist der größte Andenfuchs Südamerikas: zuhause in Wüste, Wald und Schnee gleichermaßen. Wir haben seinen Namen gewählt, weil wir Outdoor-Bekleidung genauso verstehen — ein Stück, das dich über unterschiedliches Terrain begleitet.",
      "about.mission.title": "Warum es uns gibt",
      "about.mission.body": "Chile hat eine der extremsten und vielfältigsten Geografien der Welt, doch die meiste hier verkaufte Outdoor-Bekleidung wird auf einer anderen Hemisphäre, für ein anderes Klima entworfen. Culpeo entwirft aus dem Gebiet heraus, das sie tatsächlich tragen wird.",
      "about.craft.title": "Wie wir arbeiten",
      "about.craft.body": "Wir entwerfen jedes Modell in Chile: Farbpalette, Name und Stickerei entstehen hier, auf einer bereits bewährten Qualitätsbasis. Wir arbeiten in kleinen Chargen, um jedes Detail zu kontrollieren, bevor wir etwas Neues starten.",
      "about.origin.title": "Wir stehen noch am Anfang",
      "about.origin.body": "Culpeo ist eine junge Marke. Jede Kollektion, die wir starten, wird ehrgeiziger sein als die letzte — und jede trägt den Namen eines Ortes, der es wert ist, geschützt zu werden.",
      "sizeguide.kicker": "Anleitung", "sizeguide.title": "Größenberater",
      "sizeguide.intro": "Alle unsere Caps haben eine Snapback-Trucker-Struktur: Einheitsgröße, hinten verstellbar. So passt sie den meisten erwachsenen Kopfformen, ohne an Halt zu verlieren.",
      "sizeguide.howto.title": "So misst du deinen Kopf",
      "sizeguide.howto.body": "Lege ein Maßband knapp über Ohren und Augenbrauen um deinen Kopf. Diese Zahl in Zentimetern ist deine Referenz — alle unsere Caps decken diesen Bereich mit dem Snapback ab.",
      "sizeguide.table.size": "Größe", "sizeguide.table.range": "Kopfumfang", "sizeguide.table.fit": "Passform",
      "sizeguide.adjustable.name": "Einheitsgröße, verstellbar",
      "sizeguide.adjustable.fit": "6-Positionen-Snapback — passt bequem über die gesamte Bandbreite",
      "sizeguide.tip.title": "Ein Detail, das hilft",
      "sizeguide.tip.body": "Liegst du zwischen zwei Snap-Positionen, lass die Cap etwas lockerer: Das Rückenmesh passt sich mit der Zeit von selbst an.",
      "cart.title": "Dein Warenkorb", "cart.empty": "Dein Warenkorb ist derzeit leer.", "cart.emptyCta": "Kollektion ansehen",
      "cart.item.remove": "Entfernen", "cart.item.color": "Farbe", "cart.item.qty": "Menge",
      "cart.subtotal": "Zwischensumme", "cart.total": "Gesamt", "cart.checkout": "Per WhatsApp abschließen",
      "cart.checkoutNote": "Beim Abschluss öffnet sich WhatsApp mit den Details deiner Bestellung. Zahlung und Versand klären wir direkt mit dir.",
      "cart.continue": "Weiter einkaufen",
      "credits.title": "Bildnachweise",
      "credits.intro": "Bilder unter Creative-Commons-Lizenzen, via Openverse / Wikimedia Commons.",
      "credits.back": "Zurück zur Startseite",
      "footer.faq": "Häufige Fragen",
      "faq.kicker": "Hilfe", "faq.title": "Häufige Fragen",
      "faq.intro": "Was uns am häufigsten vor dem Kauf gefragt wird. Deine Frage ist nicht dabei? Schreib uns auf WhatsApp.",
      "howtobuy.kicker": "So bestellst du", "howtobuy.title": "Vom Warenkorb zu dir nach Hause, in 3 Schritten",
      "howtobuy.step1.title": "1. Wähle dein Stück", "howtobuy.step1.body": "Füge es mit Farbe und gewünschter Menge zum Warenkorb hinzu.",
      "howtobuy.step2.title": "2. Bestellung prüfen", "howtobuy.step2.body": "Passe Mengen an oder entferne Artikel vor dem Abschluss.",
      "howtobuy.step3.title": "3. Per WhatsApp abschließen", "howtobuy.step3.body": "WhatsApp öffnet sich mit deiner fertigen Bestellung. Dort klären wir Zahlung und Versand.",
      "product.stock.low": "Nur noch wenige", "product.stock.soldOut": "Ausverkauft"
    },
    fr: {
      "brand.tagline": "Vêtements outdoor, pour ceux qui choisissent leur propre terrain.",
      "nav.home": "Accueil", "nav.products": "Boutique", "nav.about": "À propos",
      "nav.sizeguide": "Guide des tailles", "nav.cart": "Panier",
      "nav.language": "Langue",
      "hero.kicker": "Culpeo · Inspiré par la nature",
      "hero.title.line1": "Fait pour explorer.", "hero.title.line2": "Conçu pour durer.",
      "hero.subtitle": "Pièces en édition limitée, inspirées par la nature : paysages, flore et faune des quatre coins du monde.",
      "hero.cta.shop": "Voir la collection",
      "manifesto.kicker": "Origine",
      "manifesto.title": "Nous ne dessinons pas pour la ville. Nous dessinons pour la route qui en sort.",
      "manifesto.body": "Culpeo est né au Chili, entre le désert le plus aride du monde et les glaces australes — et regarde de là vers le reste de la planète. Chaque pièce est pensée pour celui qui ne reste pas immobile : l'explorateur du week-end, le voyageur qui traverse les frontières, celui qui préfère un nouveau paysage à une vitrine.",
      "pillars.materials.title": "Une base solide",
      "pillars.materials.body": "Nous partons de bases déjà éprouvées et fiables. C'est là que nous mettons l'effort : le design, la palette et la broderie — pas des promesses techniques dont vous n'avez pas besoin.",
      "pillars.design.title": "Design avec origine",
      "pillars.design.body": "Palettes, noms et formes puisés dans la nature — paysages, flore et faune des quatre coins du monde — pas dans une tendance saisonnière.",
      "pillars.exclusivity.title": "Séries limitées",
      "pillars.exclusivity.body": "Nous produisons en petits lots. Une fois une pièce épuisée, elle ne revient pas dans la même version.",
      "featured.kicker": "Collection actuelle", "featured.title": "Pièces Culpeo", "featured.cta": "Voir tout le catalogue",
      "ctaFinal.title": "Réservez votre pièce avant l'épuisement du lot.",
      "ctaFinal.body": "Écrivez-nous sur WhatsApp — nous réglons taille, couleur et livraison directement avec vous.",
      "ctaFinal.button": "Écrire sur WhatsApp",
      "footer.tagline": "Marque de vêtements outdoor.",
      "footer.explore": "Explorer", "footer.social": "Suivez-nous", "footer.credits": "Crédits photo",
      "footer.rights": "Tous droits réservés.",
      "products.kicker": "Catalogue", "products.title": "Pièces Culpeo",
      "products.subtitle": "Design original, produit en lots limités.",
      "product.addToCart": "Ajouter au panier", "product.viewDetail": "Voir le détail", "product.from": "Dès",
      "product.materialText": "Structure trucker 5 panneaux, base Yupoong Retro Trucker, snapback ajustable 6 positions, filet arrière respirant, visière pré-courbée.",
      "productDetail.back": "Retour au catalogue", "productDetail.material": "Matière",
      "productDetail.sizing": "Quelle taille choisir ?", "productDetail.sizingLink": "Voir le guide des tailles",
      "productDetail.color": "Couleur", "productDetail.quantity": "Quantité",
      "productDetail.addToCart": "Ajouter au panier", "productDetail.added": "Ajouté au panier",
      "productDetail.descriptionHeading": "Détail",
      "productDetail.careHeading": "Entretien",
      "productDetail.careBody": "Laver à la main à l'eau froide. Ne pas mettre au sèche-linge. Laisser sécher à l'ombre sur sa forme pour conserver la courbe de la visière.",
      "about.kicker": "À propos", "about.title": "Culpeo — comme le renard qui traverse tous les terrains",
      "about.intro": "Le culpeo est le plus grand renard andin d'Amérique du Sud : aussi à l'aise dans le désert, la forêt et la neige. Nous avons pris son nom parce que c'est ainsi que nous concevons le vêtement outdoor — une seule pièce, capable de vous suivre sur des terrains différents.",
      "about.mission.title": "Pourquoi nous existons",
      "about.mission.body": "Le Chili possède l'une des géographies les plus extrêmes et diverses de la planète, pourtant la plupart des vêtements outdoor vendus ici sont conçus sur un autre hémisphère, pour un autre climat. Culpeo conçoit depuis le territoire qui le portera réellement.",
      "about.craft.title": "Comment nous travaillons",
      "about.craft.body": "Nous concevons chaque modèle au Chili : palette, nom et broderie naissent ici, sur une base de qualité déjà éprouvée sur le marché. Nous travaillons en petits lots, pour contrôler chaque détail avant de lancer quelque chose de nouveau.",
      "about.origin.title": "Nous n'en sommes qu'au début",
      "about.origin.body": "Culpeo est une jeune marque. Chaque collection que nous lancerons sera plus ambitieuse que la précédente — et chacune portera le nom d'un lieu qui mérite d'être protégé.",
      "sizeguide.kicker": "Guide", "sizeguide.title": "Guide des tailles",
      "sizeguide.intro": "Toutes nos casquettes ont une structure trucker snapback : taille unique, ajustable à l'arrière. Elle convient ainsi à la plupart des têtes adultes sans perdre son maintien.",
      "sizeguide.howto.title": "Comment mesurer votre tête",
      "sizeguide.howto.body": "Avec un mètre ruban, entourez votre tête juste au-dessus des oreilles et des sourcils. Ce chiffre en centimètres est votre référence — toutes nos casquettes couvrent cette plage avec le snapback.",
      "sizeguide.table.size": "Taille", "sizeguide.table.range": "Circonférence", "sizeguide.table.fit": "Ajustement",
      "sizeguide.adjustable.name": "Taille unique ajustable",
      "sizeguide.adjustable.fit": "Snapback à 6 positions — s'ajuste confortablement d'un bout à l'autre",
      "sizeguide.tip.title": "Un détail qui aide",
      "sizeguide.tip.body": "Si vous êtes entre deux positions du snapback, laissez la casquette un peu plus lâche : le filet arrière se fait avec le temps.",
      "cart.title": "Votre panier", "cart.empty": "Votre panier est vide pour l'instant.", "cart.emptyCta": "Voir la collection",
      "cart.item.remove": "Retirer", "cart.item.color": "Couleur", "cart.item.qty": "Quantité",
      "cart.subtotal": "Sous-total", "cart.total": "Total", "cart.checkout": "Finaliser via WhatsApp",
      "cart.checkoutNote": "La finalisation ouvre WhatsApp avec le détail de votre commande. Nous réglons paiement et livraison directement avec vous.",
      "cart.continue": "Continuer mes achats",
      "credits.title": "Crédits photo",
      "credits.intro": "Images sous licences Creative Commons, via Openverse / Wikimedia Commons.",
      "credits.back": "Retour à l'accueil",
      "footer.faq": "FAQ",
      "faq.kicker": "Aide", "faq.title": "Questions fréquentes",
      "faq.intro": "Ce qu'on nous demande le plus avant d'acheter. Votre question n'y est pas ? Écrivez-nous sur WhatsApp.",
      "howtobuy.kicker": "Comment commander", "howtobuy.title": "Du panier à votre porte, en 3 étapes",
      "howtobuy.step1.title": "1. Choisissez votre pièce", "howtobuy.step1.body": "Ajoutez-la au panier avec la couleur et la quantité voulues.",
      "howtobuy.step2.title": "2. Vérifiez votre commande", "howtobuy.step2.body": "Ajustez les quantités ou retirez des articles avant de finaliser.",
      "howtobuy.step3.title": "3. Finalisez via WhatsApp", "howtobuy.step3.body": "WhatsApp s'ouvre avec votre commande prête. On y règle le paiement et la livraison.",
      "product.stock.low": "Derniers exemplaires", "product.stock.soldOut": "Épuisé"
    }
  };

  var products = [
    {
      id: "andino", slug: "trucker-andino", name: "Culpeo Trucker Andino",
      priceCLP: 24990, colorHex: { a: "#201c18", b: "#d8c7a1" }, stockStatus: "in-stock", // "in-stock" | "low" | "sold-out"
      colorLabel: { es: "Negro / Beige", en: "Black / Tan", it: "Nero / Beige", de: "Schwarz / Beige", fr: "Noir / Beige" },
      description: {
        es: "Frente negro con malla trasera beige — el equilibrio clásico de la marca, para uso diario o de cordillera.",
        en: "Black front with tan back mesh — the brand's classic balance, for daily wear or the mountains.",
        it: "Frontale nero con rete posteriore beige — l'equilibrio classico del marchio, per l'uso quotidiano o in montagna.",
        de: "Schwarzes Frontpanel mit beigem Rückenmesh — die klassische Balance der Marke, für den Alltag oder die Berge.",
        fr: "Face noire et filet arrière beige — l'équilibre classique de la marque, pour un usage quotidien ou en montagne."
      }
    },
    {
      id: "cordillera", slug: "trucker-cordillera", name: "Culpeo Trucker Cordillera",
      priceCLP: 24990, colorHex: { a: "#4b5c3a", b: "#3d4a2f" }, stockStatus: "in-stock",
      colorLabel: { es: "Verde Musgo", en: "Moss Green", it: "Verde Muschio", de: "Moosgrün", fr: "Vert Mousse" },
      description: {
        es: "Verde musgo sólido, inspirado en el bosque templado del sur de Chile.",
        en: "Solid moss green, inspired by southern Chile's temperate forest.",
        it: "Verde muschio pieno, ispirato alla foresta temperata del Cile meridionale.",
        de: "Durchgehendes Moosgrün, inspiriert vom gemäßigten Wald Südchiles.",
        fr: "Vert mousse uni, inspiré de la forêt tempérée du sud du Chili."
      }
    },
    {
      id: "altiplano", slug: "trucker-altiplano", name: "Culpeo Trucker Altiplano",
      priceCLP: 26990, colorHex: { a: "#b5652f", b: "#ede0c8" }, stockStatus: "low",
      colorLabel: { es: "Terracota / Crema", en: "Terracotta / Cream", it: "Terracotta / Crema", de: "Terrakotta / Creme", fr: "Terracotta / Crème" },
      description: {
        es: "Terracota y crema evocando los tonos del altiplano nortino. Nuestra edición más solicitada.",
        en: "Terracotta and cream evoking the tones of the northern altiplano. Our most requested edition.",
        it: "Terracotta e crema che richiamano le tonalità dell'altiplano settentrionale. La nostra edizione più richiesta.",
        de: "Terrakotta und Creme in den Farbtönen des nördlichen Altiplano. Unsere gefragteste Edition.",
        fr: "Terracotta et crème évoquant les tons de l'altiplano du nord. Notre édition la plus demandée."
      }
    },
    {
      id: "nocturno", slug: "trucker-nocturno", name: "Culpeo Trucker Nocturno",
      priceCLP: 24990, colorHex: { a: "#161412", b: "#0e0d0b" }, stockStatus: "in-stock",
      colorLabel: { es: "Negro total", en: "All black", it: "Nero totale", de: "Ganz schwarz", fr: "Tout noir" },
      description: {
        es: "Negro total, sin contrastes — la versión más minimalista del catálogo.",
        en: "All black, no contrast — the most minimal piece in the catalog.",
        it: "Nero totale, senza contrasti — la versione più minimale del catalogo.",
        de: "Ganz in Schwarz, ohne Kontraste — die minimalistischste Version im Katalog.",
        fr: "Tout noir, sans contraste — la version la plus minimaliste du catalogue."
      }
    },
    {
      id: "glaciar", slug: "trucker-glaciar", name: "Culpeo Trucker Glaciar",
      priceCLP: 26990, colorHex: { a: "#8b8f92", b: "#eef0ee" }, stockStatus: "in-stock",
      colorLabel: { es: "Gris Piedra / Blanco", en: "Stone Grey / White", it: "Grigio Pietra / Bianco", de: "Steingrau / Weiß", fr: "Gris Pierre / Blanc" },
      description: {
        es: "Gris piedra con malla blanca, inspirada en el hielo patagónico. Parche bordado en tono plata.",
        en: "Stone grey with white mesh, inspired by Patagonian ice. Silver-tone embroidered patch.",
        it: "Grigio pietra con rete bianca, ispirato al ghiaccio patagonico. Toppa ricamata color argento.",
        de: "Steingrau mit weißem Mesh, inspiriert vom patagonischen Eis. Silberfarbener Stickpatch.",
        fr: "Gris pierre et filet blanc, inspiré des glaces de Patagonie. Écusson brodé ton argent."
      }
    },
    {
      id: "desierto", slug: "trucker-desierto", name: "Culpeo Trucker Desierto",
      priceCLP: 24990, colorHex: { a: "#d9c39a", b: "#6b4a30" }, stockStatus: "in-stock",
      colorLabel: { es: "Beige / Café", en: "Sand / Brown", it: "Sabbia / Marrone", de: "Sand / Braun", fr: "Sable / Marron" },
      description: {
        es: "Beige arena con visera café, en referencia al desierto costero del norte de Chile.",
        en: "Sand beige with a brown bill, referencing northern Chile's coastal desert.",
        it: "Beige sabbia con visiera marrone, in riferimento al deserto costiero del Cile settentrionale.",
        de: "Sandbeige mit braunem Schirm, in Anlehnung an die Küstenwüste Nordchiles.",
        fr: "Beige sable et visière marron, en référence au désert côtier du nord du Chili."
      }
    }
  ];

  var faqs = [
    { id: "how-to-buy",
      question: { es: "¿Cómo compro en Culpeo?", en: "How do I buy from Culpeo?", it: "Come si acquista da Culpeo?", de: "Wie kaufe ich bei Culpeo ein?", fr: "Comment acheter chez Culpeo ?" },
      answer: { es: "Eliges tu producto, agregas el color y la cantidad al carro, y al finalizar el pedido se abre WhatsApp con el detalle armado. Ahí coordinamos pago y despacho directamente contigo.", en: "Pick your product, add the color and quantity to your cart, and when you check out WhatsApp opens with your order already put together. From there we sort payment and shipping directly with you.", it: "Scegli il tuo prodotto, aggiungi colore e quantità al carrello e, al momento di concludere l'ordine, si apre WhatsApp con il dettaglio già pronto. Da lì definiamo pagamento e spedizione direttamente con te.", de: "Wähle dein Produkt, füge Farbe und Menge zum Warenkorb hinzu — beim Abschluss öffnet sich WhatsApp mit deiner fertigen Bestellung. Dort klären wir Zahlung und Versand direkt mit dir.", fr: "Choisissez votre produit, ajoutez la couleur et la quantité au panier, et à la finalisation WhatsApp s'ouvre avec votre commande déjà prête. On y règle ensuite le paiement et la livraison directement avec vous." } },
    { id: "payment",
      question: { es: "¿Qué medios de pago aceptan?", en: "What payment methods do you accept?", it: "Quali metodi di pagamento accettate?", de: "Welche Zahlungsmethoden akzeptiert ihr?", fr: "Quels moyens de paiement acceptez-vous ?" },
      answer: { es: "Por ahora coordinamos el pago directamente por WhatsApp (transferencia u otro medio según disponibilidad). Es un paso manual mientras la tienda crece — te confirmamos todo antes de despachar.", en: "For now we coordinate payment directly over WhatsApp (bank transfer or another method depending on availability). It's a manual step while the store grows — we confirm everything before shipping.", it: "Per ora coordiniamo il pagamento direttamente su WhatsApp (bonifico o altro metodo secondo disponibilità). È un passaggio manuale mentre il negozio cresce — confermiamo tutto prima della spedizione.", de: "Aktuell klären wir die Zahlung direkt über WhatsApp (Überweisung oder eine andere Methode, je nach Verfügbarkeit). Das ist ein manueller Schritt, während der Shop wächst — wir bestätigen alles vor dem Versand.", fr: "Pour l'instant, nous coordonnons le paiement directement sur WhatsApp (virement ou autre moyen selon disponibilité). C'est une étape manuelle pendant que la boutique grandit — nous confirmons tout avant l'expédition." } },
    { id: "shipping",
      question: { es: "¿Hacen envíos a todo Chile?", en: "Do you ship all over Chile?", it: "Spedite in tutto il Cile?", de: "Versendet ihr in ganz Chile?", fr: "Livrez-vous dans tout le Chili ?" },
      answer: { es: "Sí. El costo y el tiempo de envío dependen de tu comuna — te los confirmamos por WhatsApp al coordinar tu pedido.", en: "Yes. Shipping cost and time depend on your comuna — we confirm both over WhatsApp when we coordinate your order.", it: "Sì. Costo e tempi di spedizione dipendono dalla tua zona — te li confermiamo su WhatsApp quando coordiniamo il tuo ordine.", de: "Ja. Versandkosten und -zeit hängen von deiner Gemeinde ab — wir bestätigen beides über WhatsApp, wenn wir deine Bestellung koordinieren.", fr: "Oui. Le coût et le délai de livraison dépendent de votre commune — nous les confirmons sur WhatsApp en coordonnant votre commande." } },
    { id: "delivery-time",
      question: { es: "¿Cuánto demora el despacho?", en: "How long does shipping take?", it: "Quanto tempo richiede la spedizione?", de: "Wie lange dauert der Versand?", fr: "Combien de temps prend la livraison ?" },
      answer: { es: "Como producimos en lotes limitados, el tiempo puede variar según el modelo. Te damos un plazo estimado apenas confirmamos tu pedido.", en: "Since we produce in limited batches, timing can vary by model. We give you an estimate as soon as we confirm your order.", it: "Poiché produciamo in lotti limitati, i tempi possono variare a seconda del modello. Ti diamo una stima non appena confermiamo il tuo ordine.", de: "Da wir in limitierten Chargen produzieren, kann die Zeit je nach Modell variieren. Wir geben dir eine Schätzung, sobald wir deine Bestellung bestätigen.", fr: "Comme nous produisons en lots limités, le délai peut varier selon le modèle. Nous vous donnons une estimation dès que votre commande est confirmée." } },
    { id: "exchanges",
      question: { es: "¿Puedo cambiar de talla o color?", en: "Can I exchange size or color?", it: "Posso cambiare taglia o colore?", de: "Kann ich Größe oder Farbe umtauschen?", fr: "Puis-je échanger la taille ou la couleur ?" },
      answer: { es: "Por ahora, nuestras gorras son de talla única ajustable (ver guía de tallas), así que no hay cambios de talla. Si el color no te convence, escríbenos dentro de los primeros días y vemos la mejor solución.", en: "For now, our caps are one size, adjustable (see the size guide), so there are no size exchanges. If the color isn't right, message us within the first few days and we'll find the best solution.", it: "Per ora, i nostri cappelli sono taglia unica regolabile (vedi la guida alle taglie), quindi non ci sono cambi di taglia. Se il colore non ti convince, scrivici entro i primi giorni e troviamo la soluzione migliore.", de: "Aktuell sind unsere Caps einheitsgröße, verstellbar (siehe Größenberater), daher gibt es keinen Größentausch. Wenn die Farbe nicht passt, schreib uns innerhalb der ersten Tage und wir finden die beste Lösung.", fr: "Pour l'instant, nos casquettes sont taille unique ajustable (voir le guide des tailles), il n'y a donc pas d'échange de taille. Si la couleur ne convient pas, écrivez-nous dans les premiers jours et nous trouverons la meilleure solution." } },
    { id: "defects",
      question: { es: "¿Qué pasa si mi producto llega con un defecto?", en: "What if my product arrives with a defect?", it: "Cosa succede se il mio prodotto arriva con un difetto?", de: "Was, wenn mein Produkt mit einem Mangel ankommt?", fr: "Que faire si mon produit arrive avec un défaut ?" },
      answer: { es: "Escríbenos con fotos por WhatsApp apenas la recibas y la resolvemos — cambio o devolución, lo que corresponda.", en: "Message us with photos over WhatsApp as soon as you get it and we'll sort it out — exchange or return, whichever fits.", it: "Scrivici con foto su WhatsApp appena lo ricevi e risolviamo — cambio o reso, a seconda del caso.", de: "Schreib uns mit Fotos auf WhatsApp, sobald du sie erhältst, und wir klären es — Umtausch oder Rückgabe, je nachdem.", fr: "Écrivez-nous avec des photos sur WhatsApp dès réception et nous réglons ça — échange ou retour, selon le cas." } },
    { id: "one-size",
      question: { es: "¿Todas las gorras son talla única?", en: "Are all caps one size?", it: "Tutti i cappelli sono taglia unica?", de: "Sind alle Caps einheitsgröße?", fr: "Toutes les casquettes sont-elles taille unique ?" },
      answer: { es: "Sí, todas usan snapback ajustable de 6 posiciones. Revisa la guía de tallas si tienes dudas sobre el calce.", en: "Yes, they all use a 6-position adjustable snapback. Check the size guide if you're unsure about the fit.", it: "Sì, tutti hanno uno snapback regolabile a 6 posizioni. Consulta la guida alle taglie se hai dubbi sulla vestibilità.", de: "Ja, alle haben einen 6-Positionen-Snapback. Schau im Größenberater nach, wenn du dir bei der Passform unsicher bist.", fr: "Oui, toutes ont un snapback ajustable à 6 positions. Consultez le guide des tailles en cas de doute sur l'ajustement." } }
  ];

  window.__CULPEO__ = {
    meta: {
      brand: "Culpeo",
      domain: "culpeo.cl",
      /* EDIT THESE before publishing: */
      whatsappNumber: "56962389422",      // digits only, country code first, no + or spaces
      instagram: "",                      // e.g. "https://instagram.com/tu_cuenta" — vacío = el link se oculta solo
      instagramHandle: "",
      currency: "CLP"
    },
    languages: ["es", "en", "it", "de", "fr"],
    i18n: i18n,
    products: products,
    faqs: faqs
  };
})();
